/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "error-dim": "#b92902",
        error: "#b02500",
        "on-secondary": "#fff0e7",
        background: "#f6f6f5",
        outline: "#767776",
        "on-surface": "#2d2f2f",
        "on-primary-fixed": "#204e25",
        "primary-fixed-dim": "#b6eab3",
        "surface-container-high": "#e1e3e2",
        "on-tertiary": "#f6f2ed",
        "on-secondary-fixed": "#542900",
        "on-secondary-container": "#713800",
        "tertiary-dim": "#514f4c",
        "secondary-dim": "#7d3f00",
        "surface-variant": "#dbdddc",
        "on-error-container": "#520c00",
        "secondary-fixed": "#ffc69d",
        "on-primary": "#d0ffcb",
        "surface-dim": "#d3d5d4",
        surface: "#f6f6f5",
        "inverse-surface": "#0c0f0e",
        "surface-container": "#e7e8e7",
        "on-primary-fixed-variant": "#3d6b3f",
        "primary-container": "#c4f9c0",
        "surface-tint": "#37663a",
        "error-container": "#f95630",
        secondary: "#8e4900",
        "primary-dim": "#2b592f",
        "outline-variant": "#acadac",
        "inverse-primary": "#c4f9c0",
        "tertiary-container": "#ffffff",
        "surface-container-highest": "#dbdddc",
        "tertiary-fixed": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffb37a",
        "surface-container-low": "#f0f1f0",
        "inverse-on-surface": "#9c9d9c",
        "surface-bright": "#f6f6f5",
        "on-primary-container": "#336136",
        "on-tertiary-fixed-variant": "#6f6d69",
        "on-tertiary-container": "#64625e",
        primary: "#37663a",
        "tertiary-fixed-dim": "#f4f0eb",
        "on-error": "#ffefec",
        "on-secondary-fixed-variant": "#7e4000",
        "on-background": "#2d2f2f",
        tertiary: "#5d5b58",
        "primary-fixed": "#c4f9c0",
        "on-tertiary-fixed": "#51504d",
        "on-surface-variant": "#5a5c5b",
        "secondary-container": "#ffc69d",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        body: ["Be Vietnam Pro", "system-ui", "sans-serif"],
        label: ["Be Vietnam Pro", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
